general:
  output_dir: output
  saved_dir: saved_models
dataset:
  name: batvisionv2
  dataset_dir: h:/Downloads/BatvisionV2/BatvisionV2
  location_blacklist: # List of undesried data acquistion locations
audio_feature_extraction:
  feature_name: spectrogram # melspectrogram or spectrogram
  sr: 22000
  n_fft: 256
  power: 1
  win_length: 400
  hop_length: 200
  n_mels: 16
  f_min: 0
  f_max: 20000
  to_db: False

transform:
  preprocess:  resize # resize or None
  depth_norm: True
  image_size: 256 # Image size if resize
  max_depth: 30.0 # Maximum depth value in meters

model:
  model_name: simple_unet

training:
  batch_size: 64
  load_checkpoint:
  epochs: 1
  initial_learning_rate: 0.01
  optimizer: Adam
  loss: mae
  learning_rate_scheduler: ReduceLROnPlateau




